[package]
name = "epic_shelter_generated_protos"
version = "0.0.1"
edition = "2018"

[dependencies]
prost = "0.7.0"
serde = { version = "1.0", features=["derive"] }
tonic = { version = "0.4.0", features = ["tls", "tls-roots"] }

[build-dependencies]
tonic-build = "0.4.0"
